[build]
  base = "Wyldside"
  command = "npm run build:web"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.19.4"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 8081
  publish = "web-build" 