[build]
  base = "Wyldside"
  command = "npm run build:web"
  publish = "web-build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 8081
  publish = "web-build" 